//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIndividual.PruebasConsola.PrimerServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrimerServicio.Primer_ServicioSoap")]
    public interface Primer_ServicioSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponse HelloWorld(PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponse> HelloWorldAsync(PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Primer_ServicioSoapChannel : PIndividual.PruebasConsola.PrimerServicio.Primer_ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Primer_ServicioSoapClient : System.ServiceModel.ClientBase<PIndividual.PruebasConsola.PrimerServicio.Primer_ServicioSoap>, PIndividual.PruebasConsola.PrimerServicio.Primer_ServicioSoap {
        
        public Primer_ServicioSoapClient() {
        }
        
        public Primer_ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Primer_ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Primer_ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Primer_ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponse PIndividual.PruebasConsola.PrimerServicio.Primer_ServicioSoap.HelloWorld(PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest inValue = new PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest();
            inValue.Body = new PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequestBody();
            PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponse retVal = ((PIndividual.PruebasConsola.PrimerServicio.Primer_ServicioSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponse> PIndividual.PruebasConsola.PrimerServicio.Primer_ServicioSoap.HelloWorldAsync(PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<PIndividual.PruebasConsola.PrimerServicio.HelloWorldResponse> HelloWorldAsync() {
            PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest inValue = new PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequest();
            inValue.Body = new PIndividual.PruebasConsola.PrimerServicio.HelloWorldRequestBody();
            return ((PIndividual.PruebasConsola.PrimerServicio.Primer_ServicioSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
